#!/bin/sh
# =============================================================================
# Load Test Script — API Version Traffic Generator
# =============================================================================
#
# Generates HTTP traffic to both v1 and v2 API endpoints so you can observe
# the version traffic split in Grafana dashboards and Prometheus metrics.
#
# This script runs inside a Docker container (alpine/curl). No local tools
# needed — just: docker compose --profile loadtest up loadtest
#
# Configuration via environment variables:
#   API_HOST          - API hostname:port (default: api:8080)
#   V1_WEIGHT         - Percentage of requests to v1 (default: 30)
#   V2_WEIGHT         - Percentage of requests to v2 (default: 70)
#   DURATION_SECONDS  - How long to run (default: 180)
#   REQUESTS_PER_SEC  - Target requests per second (default: 5)
# =============================================================================

set -e

# ---------------------------------------------------------------------------
# Configuration — override these with environment variables
# ---------------------------------------------------------------------------
API_HOST="${API_HOST:-api:8080}"
V1_WEIGHT="${V1_WEIGHT:-30}"
V2_WEIGHT="${V2_WEIGHT:-70}"
DURATION_SECONDS="${DURATION_SECONDS:-180}"
REQUESTS_PER_SEC="${REQUESTS_PER_SEC:-5}"

# Calculate sleep interval between requests
# Using awk because sh doesn't support floating point arithmetic
SLEEP_INTERVAL=$(awk "BEGIN {printf \"%.2f\", 1 / $REQUESTS_PER_SEC}")

# Counters
v1_count=0
v2_count=0
error_count=0
start_time=$(date +%s)

# ---------------------------------------------------------------------------
# Wait for the API to be healthy before starting the load test
# ---------------------------------------------------------------------------
echo "============================================="
echo "  API Version Traffic Generator"
echo "============================================="
echo "  Target:     http://${API_HOST}"
echo "  V1 weight:  ${V1_WEIGHT}%"
echo "  V2 weight:  ${V2_WEIGHT}%"
echo "  Duration:   ${DURATION_SECONDS}s"
echo "  Rate:       ~${REQUESTS_PER_SEC} req/s"
echo "============================================="
echo ""
echo "Waiting for API to be ready..."

retries=0
max_retries=30
until curl -sf "http://${API_HOST}/health" > /dev/null 2>&1; do
    retries=$((retries + 1))
    if [ "$retries" -ge "$max_retries" ]; then
        echo "ERROR: API not ready after ${max_retries} retries. Exiting."
        exit 1
    fi
    echo "  Attempt ${retries}/${max_retries} — waiting 2s..."
    sleep 2
done
echo "API is ready!"
echo ""

# ---------------------------------------------------------------------------
# Helper: pick a random number between 1 and 100
# Uses /dev/urandom since $RANDOM is not available in plain sh
# ---------------------------------------------------------------------------
random_1_to_100() {
    od -An -tu1 -N1 /dev/urandom | tr -d ' '
}

# ---------------------------------------------------------------------------
# Helper: pick a random action (GET list, GET by id, or POST)
# Weighted: 50% GET list, 30% GET by id, 20% POST
# ---------------------------------------------------------------------------
send_request() {
    version="$1"
    action_roll=$(random_1_to_100)

    if [ "$action_roll" -le 50 ]; then
        # GET list — the most common operation
        curl -sf "http://${API_HOST}/api/${version}/products" > /dev/null 2>&1
    elif [ "$action_roll" -le 80 ]; then
        # GET single product by ID (1, 2, or 3 from seed data)
        id=$(( ($(od -An -tu1 -N1 /dev/urandom | tr -d ' ') % 3) + 1 ))
        curl -sf "http://${API_HOST}/api/${version}/products/${id}" > /dev/null 2>&1
    else
        # POST new product
        curl -sf -X POST "http://${API_HOST}/api/${version}/products" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"LoadTest Item\",\"price\":9.99,\"category\":\"test\",\"description\":\"Generated by load test\",\"tags\":[\"loadtest\"]}" \
            > /dev/null 2>&1
    fi
}

# ---------------------------------------------------------------------------
# Main loop — run for DURATION_SECONDS, picking v1 or v2 based on weights
# ---------------------------------------------------------------------------
echo "Starting load test at $(date -u '+%Y-%m-%dT%H:%M:%SZ')..."
echo ""

last_report=0

while true; do
    now=$(date +%s)
    elapsed=$((now - start_time))

    # Stop after DURATION_SECONDS
    if [ "$elapsed" -ge "$DURATION_SECONDS" ]; then
        break
    fi

    # Progress report every 30 seconds
    if [ $((elapsed - last_report)) -ge 30 ] && [ "$elapsed" -gt 0 ]; then
        total=$((v1_count + v2_count))
        echo "[${elapsed}s] Sent ${total} requests (v1: ${v1_count}, v2: ${v2_count}, errors: ${error_count})"
        last_report=$elapsed
    fi

    # Pick v1 or v2 based on configured weights
    # Roll a number 1-100: if <= V1_WEIGHT, use v1; otherwise v2
    roll=$(random_1_to_100)

    if [ "$roll" -le "$V1_WEIGHT" ]; then
        version="v1"
        if send_request "v1"; then
            v1_count=$((v1_count + 1))
        else
            error_count=$((error_count + 1))
        fi
    else
        version="v2"
        if send_request "v2"; then
            v2_count=$((v2_count + 1))
        else
            error_count=$((error_count + 1))
        fi
    fi

    # Throttle to target requests per second
    sleep "$SLEEP_INTERVAL"
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
total=$((v1_count + v2_count))
echo ""
echo "============================================="
echo "  Load Test Complete"
echo "============================================="
echo "  Duration:     ${DURATION_SECONDS}s"
echo "  Total sent:   ${total} requests"
echo "  V1 requests:  ${v1_count}"
echo "  V2 requests:  ${v2_count}"
echo "  Errors:       ${error_count}"
if [ "$total" -gt 0 ]; then
    v1_pct=$(awk "BEGIN {printf \"%.1f\", ($v1_count / $total) * 100}")
    v2_pct=$(awk "BEGIN {printf \"%.1f\", ($v2_count / $total) * 100}")
    echo "  V1 share:     ${v1_pct}%"
    echo "  V2 share:     ${v2_pct}%"
fi
echo "============================================="
echo ""
echo "Open Grafana at http://localhost:3000 to see the results."
echo "Dashboard: 'API Version Traffic'"
