// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product.proto
//
// This file is a simplified version of what protoc generates.
// The Docker build runs protoc to produce the full version.

package proto

// Note: The real protoc-generated code imports protoimpl for version checks
// and full proto message registration. This simplified version provides
// the types needed by server and client code.

// Product represents a product entity.
type Product struct {
	Id       int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price    float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Category string  `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *Product) GetId() int32      { if x != nil { return x.Id }; return 0 }
func (x *Product) GetName() string   { if x != nil { return x.Name }; return "" }
func (x *Product) GetPrice() float64 { if x != nil { return x.Price }; return 0 }
func (x *Product) GetCategory() string { if x != nil { return x.Category }; return "" }

// Request/Response messages

type ListProductsRequest struct{}
type ListProductsResponse struct {
	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil { return x.Products }
	return nil
}

type GetProductRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProductRequest) GetId() int32 { if x != nil { return x.Id }; return 0 }

type CreateProductRequest struct {
	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price    float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Category string  `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *CreateProductRequest) GetName() string     { if x != nil { return x.Name }; return "" }
func (x *CreateProductRequest) GetPrice() float64   { if x != nil { return x.Price }; return 0 }
func (x *CreateProductRequest) GetCategory() string { if x != nil { return x.Category }; return "" }

type UpdateProductRequest struct {
	Id       int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price    float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Category string  `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *UpdateProductRequest) GetId() int32        { if x != nil { return x.Id }; return 0 }
func (x *UpdateProductRequest) GetName() string     { if x != nil { return x.Name }; return "" }
func (x *UpdateProductRequest) GetPrice() float64   { if x != nil { return x.Price }; return 0 }
func (x *UpdateProductRequest) GetCategory() string { if x != nil { return x.Category }; return "" }

type DeleteProductRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteProductRequest) GetId() int32 { if x != nil { return x.Id }; return 0 }

type DeleteProductResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteProductResponse) GetSuccess() bool { if x != nil { return x.Success }; return false }
